version: "3.8"

services:
  tomcat:
    build: ./tomcat-app
    container_name: ${TOMCAT_CONTAINER_NAME:-tomcat-app}
    ports:
      - "${TOMCAT_PORT:-9999}:8080"
    depends_on:
      - db

  db:
    image: postgres:9.5
    container_name: ${POSTGRES_CONTAINER_NAME:-postgres95}
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_DB: ${POSTGRES_DB:-mydb}
    ports:
      - "${POSTGRES_PORT:-7777}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

