version: "3.8"

services:
  tomcat:
    build:
      context: ./tomcat-app
      args:
        TOMCAT_VERSION: ${TOMCAT_VERSION:-8.5.96}
        TOMCAT_URL: ${TOMCAT_URL:-https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.96/bin/apache-tomcat-8.5.96.tar.gz}
        TOMCAT_ADMIN_USER: ${TOMCAT_ADMIN_USER:-admin}
        TOMCAT_ADMIN_PASSWORD: ${TOMCAT_ADMIN_PASSWORD:-admin}
    ports:
      - "${TOMCAT_PORT:-9999}:8080"
    depends_on:
      - db
    environment:
      TOMCAT_PORT: ${TOMCAT_PORT:-9999}

  db:
    image: postgres:9.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Maker@1
      POSTGRES_DB: postgres
    ports:
      - "${POSTGRES_PORT:-7777}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
