version: "3.8"

services:
  tomcat:
    build: ./tomcat-app
    container_name: tomcat-app
    ports:
      - "8888:8080"
    depends_on:
      - db

  db:
    image: postgres:9.5
    container_name: postgres95
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Teste@123
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
